;;;; Run with: ciel --no-userinit tests/macos-art.lisp
(load (merge-pathnames "fixture.lisp" *load-truename*))
(in-package :twigwm-macos-input)

(let* ((spec (native-key-spec 37))
       (argv (getf spec :argv))
       (*remote-bundles* '("com.citrix.receiver.icaviewer.mac" "com.microsoft.rdc.macos"))
       (action (native-key-action spec +command+ "com.apple.finder"))
       (launch (symbol-function 'uiop:launch-program))
       (frontmost (symbol-function 'twigwm-macos-apps:frontmost))
       (calls nil))
  (assert (equal action (list :launch argv)))
  (assert (equal argv '("/opt/homebrew/bin/sbcl" "--dynamic-space-size" "4096"
                       "--script" "~/.local/bin/art" "show")))
  (assert (null (getf spec :shell)))
  (dolist (bundle *remote-bundles*)
    (assert (null (native-key-action spec +command+ bundle))))
  (dolist (flags '(0 #x80000 #x180000 #x120000 #x140000))
    (assert (null (native-key-action spec flags "com.apple.finder"))))
  (unwind-protect
       (progn
         (setf (symbol-function 'uiop:launch-program)
               (lambda (command &rest options) (push (cons command options) calls)))
         (launch-native-command argv)
         (assert (equal (first calls)
                        (list (list "/opt/homebrew/bin/sbcl" "--dynamic-space-size" "4096"
                                    "--script" (namestring (merge-pathnames ".local/bin/art"
                                                                          (user-homedir-pathname)))
                                    "show")
                              :input nil :output :interactive :error-output :interactive)))
         (format t "PASS: Command-L art, remote/modifier passthrough, direct asynchronous argv and home expansion.~%")
         (when (uiop:os-macosx-p)
           (twigwm-macos-apps::framework "ApplicationServices")
           (let ((*live* t) (*handoff* (make-handoff)) (*lease* nil)
                 (*escape-down* nil)
                 (*callback-error* nil) (*probe-seen* nil)
                 (*app-down* (make-hash-table)) (*app-actions* nil) (*app-thread* nil)
                 (bundle "com.apple.finder"))
             (setf (symbol-function 'twigwm-macos-apps:frontmost) (lambda () (values 123 bundle)))
             (assert (probe-event 37 10 +command+))
             (assert (probe-event 37 10 +command+))
             (assert (equal *app-actions* (list action)))
             (assert (probe-event 37 11 0))
             (service-apps)
             (sb-thread:join-thread *app-thread*)
             (assert (= 2 (length calls)))
             (assert (null *app-actions*))
             (dolist (remote *remote-bundles*)
               (setf bundle remote)
               (assert (not (probe-event 37 10 +command+)))
               (assert (not (probe-event 37 11 +command+))))
             (assert (zerop (hash-table-count *app-down*)))
             (assert (null *callback-error*)))
           (format t "PASS: native art dispatch consumes repeats/releases, launches once, and preserves remote keys.~%")))
    (setf (symbol-function 'uiop:launch-program) launch
          (symbol-function 'twigwm-macos-apps:frontmost) frontmost)))
(format t "ART_KEYS_COMPLETE~%")
