;;;; Run with: ciel --no-userinit tests/macos-input.lisp
(load (merge-pathnames "fixture.lisp" *load-truename*))
(in-package :twigwm-macos-input)

(let* ((handoff (make-handoff :limit 5))
       (token (arm handoff))
       (sequence '(:command-up :two-down :two-up :one-down :one-up)))
  (assert (= token (arm handoff))) ; repeat must not restart/lose the queue
  (dolist (event sequence) (enqueue handoff event))
  (assert (handler-case (progn (enqueue handoff :overflow) nil) (error () t)))
  (assert (= 5 (handoff-count handoff)))
  (assert (equal '(nil) (multiple-value-list (finish handoff (1- token)))))
  (assert (handoff-pending handoff))
  (multiple-value-bind (events ready) (finish handoff token)
    (assert ready)
    (assert (equal sequence events)))
  (assert (not (handoff-pending handoff)))
  (assert (zerop (handoff-count handoff)))
  (assert (not (finish handoff token)))
  (let ((next (arm handoff)))
    (assert (> next token))
    (enqueue handoff :new-key)
    (assert (not (finish handoff token)))
    (assert (equal '(:new-key) (finish handoff next))))
  (assert (handler-case (progn (enqueue handoff :unarmed) nil) (error () t))))

(format t "PASS: FIFO type-ahead, explicit/stale readiness, repeated prefix, bounded queue, and reset.~%")
(loop for code across #(29 18 19 20 21 23 22 26 28 25)
      do (assert (number-p code +command+))
         (dolist (flags '(0 #x120000 #x140000 #x180000))
           (assert (not (number-p code flags)))))
(assert (not (number-key 53)))
(assert (equal '(55) (command-keycodes +command+)))
(assert (equal '(54) (command-keycodes #x100010)))
(assert (equal '(55 54) (command-keycodes #x100018)))
(format t "PASS: Command 1-9 route to desktop, zero is separate, extra modifiers pass through, held Command sides preserved.~%")

;; Focus the saved desktop device and place that session before releasing input.
(let ((saved-device (symbol-function 'twigwm-macos-apps:open-saved-device))
      (place (symbol-function 'twigwm-macos-apps:place-bundle))
      (calls nil))
  (unwind-protect
       (progn
         (setf (symbol-function 'twigwm-macos-apps:open-saved-device)
               (lambda (name)
                 (assert (equal name "desktop"))
                 (push :desktop calls)
                 (values 123 "com.microsoft.rdc.macos"))
               (symbol-function 'twigwm-macos-apps:place-bundle)
               (lambda (bundle region &optional pid)
                 (assert (eq region :laptop))
                 (assert (equal bundle "com.microsoft.rdc.macos"))
                 (assert (= pid 123))
                 (push :place calls)))
         (let ((lease (make-lease :device "desktop")))
           (lease-worker lease)
           (assert (not (lease-error lease)))
           (assert (and (lease-ready lease) (lease-finished lease)))
           (assert (equal (lease-bundle lease) "com.microsoft.rdc.macos"))
           (assert (= (lease-pid lease) 123)))
         (assert (equal calls '(:place :desktop)))
         ;; Failed focus must never make the buffered input ready.
         (setf (symbol-function 'twigwm-macos-apps:open-saved-device)
               (lambda (name) (declare (ignore name)) (error "Device unavailable")))
         (let ((lease (make-lease)))
           (lease-worker lease)
           (assert (lease-error lease))
           (assert (lease-finished lease))
           (assert (not (lease-ready lease)))))
    (setf (symbol-function 'twigwm-macos-apps:open-saved-device) saved-device
          (symbol-function 'twigwm-macos-apps:place-bundle) place)))
(format t "PASS: desktop saved-device focus/placement and failed-focus buffering gate.~%")

;; A new prefix can replace a cancelled focus operation without blocking the tap.
(let* ((worker (symbol-function 'lease-worker))
       (gate (sb-thread:make-semaphore)) (calls nil)
       (previous (make-lease :cancelled t))
       (*lease* previous) (next nil))
  (setf (lease-thread previous)
        (sb-thread:make-thread
         (lambda () (sb-thread:wait-on-semaphore gate) (push :old calls))))
  (unwind-protect
       (progn
         (setf (symbol-function 'lease-worker)
               (lambda (lease) (assert (eq lease next)) (push :new calls)))
         (start-transfer)
         (setf next *lease*)
         (assert (not (eq next previous)))
         (assert (null calls))
         (sb-thread:signal-semaphore gate)
         (sb-thread:join-thread (lease-thread next))
         (assert (equal (reverse calls) '(:old :new))))
    (sb-thread:signal-semaphore gate)
    (sb-thread:join-thread (lease-thread previous))
    (when next (sb-thread:join-thread (lease-thread next)))
    (setf (symbol-function 'lease-worker) worker)))
(format t "PASS: cancelled handoffs finish before replacement focus, without blocking input.~%")

(when (uiop:os-macosx-p) (probe))

;; Tab adapter pins the destination, cancels handoffs, and releases on shutdown.
(let ((frontmost (symbol-function 'twigwm-macos-apps:frontmost))
      (post-chord (symbol-function 'post-key-chord))
      (*handoff* (make-handoff)) (*lease* (make-lease))
      (*tab-switch* nil)
      (*remote-bundles* '("com.microsoft.rdc.macos")) (posted nil))
  (unwind-protect
       (progn
         (setf (symbol-function 'twigwm-macos-apps:frontmost)
               (lambda () (values 123 "com.microsoft.rdc.macos"))
               (symbol-function 'post-key-chord)
               (lambda (pid chord) (push (list pid chord) posted)))
         (arm *handoff*)
         (assert (dispatch-tab-switch 48 10 #x100008))
         (assert (lease-cancelled-p *lease*))
         (assert (not (handoff-pending *handoff*)))
         (assert (equal (first posted)
                        '(123 ((55 12 0) (58 12 #x80020) (48 10 #x80020)))))
         (release-tab-switch)
         (assert (equal (first posted) '(123 ((48 11 0) (58 12 0)))))
         (assert (not *tab-switch*))
         (assert (dispatch-tab-switch 48 10 #x80020))
         (assert (null (caar posted))) ; local switcher uses global delivery
         (release-tab-switch)
         (assert (equal (first posted) '(nil ((48 11 0) (55 12 0)))))
         ;; On macOS, also exercise callback priority and the replay guard.
         (when (uiop:os-macosx-p)
           (let ((*live* t) (*swap-tab-modifiers* t) (*callback-error* nil))
             (assert (probe-event 48 10 #x100008))
             (assert (probe-event 48 11 #x100008))
             (assert (probe-event 55 12 0))
             (assert (not *tab-switch*))
             (assert (probe-event 48 10 #x80020))
             (assert (not (probe-event 48 10 #x100008 +tab-tag+)))
             (assert (probe-event 58 12 0))
             (assert (probe-event 48 11 0))
             (assert (not *tab-switch*))
             (assert (not *callback-error*)))))
    (setf (symbol-function 'twigwm-macos-apps:frontmost) frontmost
          (symbol-function 'post-key-chord) post-chord)))
(format t "PASS: Tab adapter routing, handoff cancellation, and shutdown releases.~%")


;; Native callback routing, with no worker, guest command, or app delivery.
(when (uiop:os-macosx-p)
  (let ((start (symbol-function 'start-transfer))
        (frontmost (symbol-function 'twigwm-macos-apps:frontmost))
        (post (symbol-function 'post-to-app)))
    (unwind-protect
         (loop for code across #(29 18 19 20 21 23 22 26 28 25) do
           (let ((*live* t) (*handoff* (make-handoff)) (*lease* nil) (*escape-down* nil)
                 (*callback-error* nil) (*probe-seen* nil)
                 (*remote-bundles* '("com.microsoft.rdc.macos" "com.citrix.receiver.icaviewer.mac"))
                 (bundle "com.microsoft.rdc.macos")
                 (*app-down* (make-hash-table)) (*app-actions* nil)
                 (targets nil) (posted nil))
             (setf (symbol-function 'start-transfer)
                   (lambda (&optional (device *number-device*))
                     (push device targets)
                     (setf *lease* (make-lease)))
                   (symbol-function 'twigwm-macos-apps:frontmost)
                   (lambda () (values 123 bundle))
                   (symbol-function 'post-to-app)
                   (lambda (pid event)
                     (assert (= 123 pid))
                     (push (event-description event) posted)))
             ;; Ordinary remote numbers retain guest ownership.
             (dolist (remote *remote-bundles*)
               (setf bundle remote)
               (dolist (type '(10 10 11))
                 (multiple-value-bind (consumed description)
                     (probe-event code type +command+)
                   (assert (not consumed))
                   (assert (equal description (list code type +command+))))))
             (assert (null targets))
             ;; Native Mac numbers route to their device; zero has its own.
             (setf bundle "com.apple.finder")
             (assert (probe-event code 10 +command+))
             (assert (probe-event code 11 +command+))
             (assert (probe-event 55 12 0))
             (assert (equal targets (list (if (= code 29) "secondary" "desktop"))))
             (setf (lease-finished *lease*) t (lease-ready *lease*) t
                   (lease-pid *lease*) 123 (lease-bundle *lease*) "com.microsoft.rdc.macos")
             (service-tick)
             (assert (null *lease*))
             (assert (equal (reverse posted)
                            `((55 12 ,+command+) (,code 10 ,+command+)
                              (,code 11 ,+command+) (55 12 0))))
             (assert (not *callback-error*))
             (cancel)))
      (setf (symbol-function 'start-transfer) start
            (symbol-function 'twigwm-macos-apps:frontmost) frontmost
            (symbol-function 'post-to-app) post)))
  (format t "PASS: remote numbers pass through; native numbers route, zero to its own device.~%"))

;; Command-Escape is one local action: previous window, consumed, even from a remote.
(when (uiop:os-macosx-p)
  (let ((frontmost (symbol-function 'twigwm-macos-apps:frontmost))
        (*live* t) (*handoff* (make-handoff)) (*lease* (make-lease))
        (*escape-down* nil) (*callback-error* nil) (*probe-seen* nil)
        (*remote-bundles* '("com.microsoft.rdc.macos"))
        (*app-down* (make-hash-table)) (*app-actions* nil))
    (unwind-protect
         (progn
           (setf (symbol-function 'twigwm-macos-apps:frontmost)
                 (lambda () (values 123 "com.microsoft.rdc.macos")))
           (arm *handoff*)
           (assert (probe-event 53 10 +command+))
           (assert (probe-event 53 10 +command+)) ; held repeat does not switch again
           (assert (probe-event 53 11 +command+))
           (assert (equal *app-actions* '((:previous-window))))
           (assert (lease-cancelled-p *lease*)) ; and cancels a pending handoff
           (assert (not (handoff-pending *handoff*)))
           (setf *app-actions* nil)
           (assert (not (probe-event 18 10 +command+))) ; next number goes to the remote
           (assert (not (probe-event 53 10 0)))         ; bare Escape stays with the app
           (assert (not (probe-event 53 11 0)))
           (assert (null *app-actions*))
           (assert (not *callback-error*)))
      (cancel)
      (setf (symbol-function 'twigwm-macos-apps:frontmost) frontmost)))
  (format t "PASS: Command-Escape returns at once, consumes repeats, cancels handoffs, and leaves other keys alone.~%"))
(format t "MACOS_INPUT_COMPLETE~%")
