;;;; Run with: ciel --no-userinit tests/macos-input.lisp
(load (merge-pathnames "fixture.lisp" *load-truename*))
(in-package :twigwm-macos-input)

(let* ((handoff (make-handoff :limit 5))
       (token (arm handoff))
       (sequence '(:command-up :two-down :two-up :one-down :one-up)))
  (assert (= token (arm handoff))) ; repeat must not restart/lose the queue
  (dolist (event sequence) (enqueue handoff event))
  (assert (handler-case (progn (enqueue handoff :overflow) nil) (error () t)))
  (assert (= 5 (handoff-count handoff)))
  (assert (equal '(nil) (multiple-value-list (finish handoff (1- token)))))
  (assert (handoff-pending handoff))
  (multiple-value-bind (events ready) (finish handoff token)
    (assert ready)
    (assert (equal sequence events)))
  (assert (not (handoff-pending handoff)))
  (assert (zerop (handoff-count handoff)))
  (assert (not (finish handoff token)))
  (let ((next (arm handoff)))
    (assert (> next token))
    (enqueue handoff :new-key)
    (assert (not (finish handoff token)))
    (assert (equal '(:new-key) (finish handoff next))))
  (assert (handler-case (progn (enqueue handoff :unarmed) nil) (error () t))))

(format t "PASS: FIFO type-ahead, explicit/stale readiness, repeated prefix, bounded queue, and reset.~%")
(loop for code across #(29 18 19 20 21 23 22 26 28 25)
      do (assert (eql (/= code 29) (not (null (number-p code +command+)))))
         (dolist (flags '(0 #x120000 #x140000 #x180000))
           (assert (not (number-p code flags)))))
(assert (not (number-key 53)))
(assert (equal '(55) (command-keycodes +command+)))
(assert (equal '(54) (command-keycodes #x100010)))
(assert (equal '(55 54) (command-keycodes #x100018)))
(format t "PASS: Command 1-9 route to desktop, zero is separate, extra modifiers pass through, held Command sides preserved.~%")

;; Focus the saved desktop device and place that session before releasing input.
(let ((saved-device (symbol-function 'twigwm-macos-apps:open-saved-device))
      (place (symbol-function 'twigwm-macos-apps:place-bundle))
      (calls nil))
  (unwind-protect
       (progn
         (setf (symbol-function 'twigwm-macos-apps:open-saved-device)
               (lambda (name)
                 (assert (equal name "desktop"))
                 (push :desktop calls)
                 (values 123 "com.microsoft.rdc.macos"))
               (symbol-function 'twigwm-macos-apps:place-bundle)
               (lambda (bundle region &optional pid)
                 (assert (eq region :laptop))
                 (assert (equal bundle "com.microsoft.rdc.macos"))
                 (assert (= pid 123))
                 (push :place calls)))
         (let ((lease (make-lease)))
           (lease-worker lease)
           (assert (not (lease-error lease)))
           (assert (and (lease-ready lease) (lease-finished lease)))
           (assert (equal (lease-bundle lease) "com.microsoft.rdc.macos"))
           (assert (= (lease-pid lease) 123)))
         (assert (equal calls '(:place :desktop)))
         ;; Failed focus must never make the buffered input ready.
         (setf (symbol-function 'twigwm-macos-apps:open-saved-device)
               (lambda (name) (declare (ignore name)) (error "Device unavailable")))
         (let ((lease (make-lease)))
           (lease-worker lease)
           (assert (lease-error lease))
           (assert (lease-finished lease))
           (assert (not (lease-ready lease)))))
    (setf (symbol-function 'twigwm-macos-apps:open-saved-device) saved-device
          (symbol-function 'twigwm-macos-apps:place-bundle) place)))
(format t "PASS: desktop saved-device focus/placement and failed-focus buffering gate.~%")

;; A new prefix can replace a cancelled focus operation without blocking the tap.
(let* ((worker (symbol-function 'lease-worker))
       (gate (sb-thread:make-semaphore)) (calls nil)
       (previous (make-lease :cancelled t))
       (*lease* previous) (next nil))
  (setf (lease-thread previous)
        (sb-thread:make-thread
         (lambda () (sb-thread:wait-on-semaphore gate) (push :old calls))))
  (unwind-protect
       (progn
         (setf (symbol-function 'lease-worker)
               (lambda (lease) (assert (eq lease next)) (push :new calls)))
         (start-transfer)
         (setf next *lease*)
         (assert (not (eq next previous)))
         (assert (null calls))
         (sb-thread:signal-semaphore gate)
         (sb-thread:join-thread (lease-thread next))
         (assert (equal (reverse calls) '(:old :new))))
    (sb-thread:signal-semaphore gate)
    (sb-thread:join-thread (lease-thread previous))
    (when next (sb-thread:join-thread (lease-thread next)))
    (setf (symbol-function 'lease-worker) worker)))
(format t "PASS: cancelled handoffs finish before replacement focus, without blocking input.~%")

(when (uiop:os-macosx-p) (probe))

;; Tab adapter pins the destination, cancels handoffs, and releases on shutdown.
(let ((frontmost (symbol-function 'twigwm-macos-apps:frontmost))
      (post-chord (symbol-function 'post-key-chord))
      (*handoff* (make-handoff)) (*lease* (make-lease))
      (*host-prefix-p* t) (*tab-switch* nil)
      (*remote-bundles* '("com.microsoft.rdc.macos")) (posted nil))
  (unwind-protect
       (progn
         (setf (symbol-function 'twigwm-macos-apps:frontmost)
               (lambda () (values 123 "com.microsoft.rdc.macos"))
               (symbol-function 'post-key-chord)
               (lambda (pid chord) (push (list pid chord) posted)))
         (arm *handoff*)
         (assert (dispatch-tab-switch 48 10 #x100008))
         (assert (lease-cancelled-p *lease*))
         (assert (not (handoff-pending *handoff*)))
         (assert (not *host-prefix-p*))
         (assert (equal (first posted)
                        '(123 ((55 12 0) (58 12 #x80020) (48 10 #x80020)))))
         (release-tab-switch)
         (assert (equal (first posted) '(123 ((48 11 0) (58 12 0)))))
         (assert (not *tab-switch*))
         (assert (dispatch-tab-switch 48 10 #x80020))
         (assert (null (caar posted))) ; local switcher uses global delivery
         (release-tab-switch)
         (assert (equal (first posted) '(nil ((48 11 0) (55 12 0)))))
         ;; On macOS, also exercise callback priority and the replay guard.
         (when (uiop:os-macosx-p)
           (let ((*live* t) (*swap-tab-modifiers* t) (*callback-error* nil))
             (assert (probe-event 48 10 #x100008))
             (assert (probe-event 48 11 #x100008))
             (assert (probe-event 55 12 0))
             (assert (not *tab-switch*))
             (assert (probe-event 48 10 #x80020))
             (assert (not (probe-event 48 10 #x100008 +tab-tag+)))
             (assert (probe-event 58 12 0))
             (assert (probe-event 48 11 0))
             (assert (not *tab-switch*))
             (assert (not *callback-error*)))))
    (setf (symbol-function 'twigwm-macos-apps:frontmost) frontmost
          (symbol-function 'post-key-chord) post-chord)))
(format t "PASS: Tab adapter routing, prefix/handoff cancellation, and shutdown releases.~%")

;; Command-0 is consumed without replaying a zero or starting a desktop transfer.
(when (uiop:os-macosx-p)
  (let ((*live* t) (*handoff* (make-handoff)) (*lease* (make-lease))
        (*escape-down* nil) (*host-prefix-p* nil)
        (*callback-error* nil) (*probe-seen* nil)
        (*app-down* (make-hash-table)) (*app-actions* nil))
    (assert (not (probe-event 29 10 #x120000))) ; Shift-Command-0 stays native.
    (arm *handoff*) ; zero also cancels an in-flight desktop handoff.
    (assert (probe-event 29 10 +command+))
    (assert (probe-event 29 10 +command+)) ; held repeat does not reopen secondary.
    (assert (probe-event 29 11 +command+))
    (assert (equal *app-actions* '((:saved-device "secondary"))))
    (assert (lease-cancelled-p *lease*))
    (assert (not (handoff-pending *handoff*)))
    (assert (zerop (hash-table-count *app-down*)))
    (assert (not *callback-error*)))
  (format t "PASS: Command-0 opens secondary directly once, consumes repeats/releases, and cancels pending desktop routing.~%"))

;; Native callback routing, with no worker, guest command, or app delivery.
(when (uiop:os-macosx-p)
  (let ((start (symbol-function 'start-transfer))
        (frontmost (symbol-function 'twigwm-macos-apps:frontmost))
        (post (symbol-function 'post-to-app)))
    (unwind-protect
         (loop for code across #(18 19 20 21 23 22 26 28 25) do
           (let ((*live* t) (*handoff* (make-handoff)) (*lease* nil)
                 (*escape-down* nil) (*host-prefix-p* nil)
                 (*callback-error* nil) (*probe-seen* nil)
                 (*remote-bundles* '("com.microsoft.rdc.macos" "com.citrix.receiver.icaviewer.mac"))
                 (bundle "com.microsoft.rdc.macos")
                 (*app-down* (make-hash-table)) (*app-actions* nil)
                 (targets nil) (posted nil))
             (setf (symbol-function 'start-transfer)
                   (lambda ()
                     (push :desktop targets)
                     (setf *lease* (make-lease)))
                   (symbol-function 'twigwm-macos-apps:frontmost)
                   (lambda () (values 123 bundle))
                   (symbol-function 'post-to-app)
                   (lambda (pid event)
                     (assert (= 123 pid))
                     (push (event-description event) posted)))
             (labels ((prefix ()
                        (assert (probe-event 53 10 +command+))
                        (assert (probe-event 53 10 +command+)) ; repeat
                        (assert (probe-event 53 11 0)) ; Command may release first
                        (assert *host-prefix-p*)
                        (assert (null posted)))
                      (finish-transfer ()
                        (setf (lease-finished *lease*) t (lease-ready *lease*) t
                              (lease-pid *lease*) 123
                              (lease-bundle *lease*) "com.microsoft.rdc.macos")
                        (service-tick)
                        (assert (null *lease*))
                        (assert (not (handoff-pending *handoff*)))))
               ;; Ordinary remote numbers retain guest ownership.
               (dolist (remote *remote-bundles*)
                 (setf bundle remote)
                 (dolist (type '(10 10 11))
                   (multiple-value-bind (consumed description)
                       (probe-event code type +command+)
                     (assert (not consumed))
                     (assert (equal description (list code type +command+)))))
                 ;; After the local prefix, force the same desktop assignment.
                 (prefix)
                 (assert (not (probe-event 55 12 0)))
                 (assert (not (probe-event 55 12 +command+)))
                 (assert *host-prefix-p*)
                 (assert (probe-event code 10 +command+))
                 (assert (not *host-prefix-p*))
                 (assert (probe-event code 11 +command+))
                 (assert (probe-event 55 12 0))
                 (finish-transfer)
                 (assert (equal (reverse posted)
                                `((55 12 ,+command+) (,code 10 ,+command+)
                                  (,code 11 ,+command+) (55 12 0))))
                 (assert (null *app-actions*))
                 (setf posted nil))
               (assert (equal targets '(:desktop :desktop)))
               ;; Native Mac numbers keep using the existing desktop rule.
               (setf bundle "com.apple.finder" targets nil)
               (assert (probe-event code 10 +command+))
               (assert (probe-event code 11 +command+))
               ;; A prefix takes over even while the previous number is queued.
               (let ((old *lease*))
                 (prefix)
                 (assert (lease-cancelled-p old))
                 (assert (not (handoff-pending *handoff*)))
                 (assert (probe-event 18 10 +command+))
                 (assert (not (eq old *lease*))))
               (assert (probe-event 18 11 +command+))
               (assert (probe-event 55 12 0))
               (assert (equal targets '(:desktop :desktop)))
               (finish-transfer)
               (assert (equal (reverse posted)
                              `((55 12 ,+command+) (18 10 ,+command+)
                                (18 11 ,+command+) (55 12 0))))
               (assert (not *callback-error*))
               (cancel))))
      (setf (symbol-function 'start-transfer) start
            (symbol-function 'twigwm-macos-apps:frontmost) frontmost
            (symbol-function 'post-to-app) post)))
  (format t "PASS: local Escape consumes its chord, forces all desktop numbers, preserves ordinary remote keys, and replaces queued input.~%"))

;; The local reader consumes unknown keys and supports cancellation and native actions.
(when (uiop:os-macosx-p)
  (let ((frontmost (symbol-function 'twigwm-macos-apps:frontmost))
        (post-chord (symbol-function 'post-key-chord)) (chords nil)
        (*live* t) (*handoff* (make-handoff)) (*lease* nil)
        (*escape-down* nil) (*host-prefix-p* nil)
        (*callback-error* nil) (*probe-seen* nil)
        (*remote-bundles* '("com.microsoft.rdc.macos"))
        (*app-down* (make-hash-table)) (*app-actions* nil))
    (unwind-protect
         (progn
           (setf (symbol-function 'twigwm-macos-apps:frontmost)
                 (lambda () (values 123 "com.microsoft.rdc.macos"))
                 (symbol-function 'post-key-chord)
                 (lambda (pid chord) (push (list pid chord) chords)))
           (flet ((prefix ()
                    (assert (probe-event 53 10 +command+))
                    (assert (probe-event 53 11 +command+))
                    (assert *host-prefix-p*)))
             ;; The complete prefix repeated selects the previous individual window.
             (prefix)
             (assert (probe-event 53 10 +command+))
             (assert (probe-event 53 10 +command+)) ; no repeated switching while held
             (assert (probe-event 53 11 +command+))
             (assert (not *host-prefix-p*))
             (assert (equal *app-actions* '((:previous-window))))
             (setf *app-actions* nil)
             (prefix)
             (dolist (type '(10 10 11)) (assert (probe-event 0 type 0))) ; unbound A
             (assert (not *host-prefix-p*))
             (assert (not (probe-event 0 10 0))) ; next key goes to the app
             (assert (not (probe-event 0 11 0)))
             (prefix)
             (assert (probe-event 53 10 0)) ; bare Escape sends the prefix
             (assert (probe-event 53 10 0)) ; held repeat is consumed
             (assert (probe-event 53 11 0))
             (assert (equal chords '((123 ((55 12 #x100008) (53 10 #x100008)
                                          (53 11 #x100008) (55 12 0))))))
             (assert (not *host-prefix-p*))
             (prefix)
             (assert (probe-event 5 10 #x40000)) ; Control-G cancels
             (assert (probe-event 5 11 #x40000))
             (assert (= 1 (length chords)))
             (assert (not *host-prefix-p*))
             (prefix)
             (assert (not (probe-event 48 10 +command+))) ; native Command-Tab
             (assert (not *host-prefix-p*))
             (prefix)
             (cancel) ; the click path calls the same cancellation
             (assert (not *host-prefix-p*))
             ;; Prefix zero still opens secondary once, with no guest handoff.
             (prefix)
             (dolist (type '(10 10 11)) (assert (probe-event 29 type +command+)))
             (assert (equal *app-actions* '((:saved-device "secondary"))))
             (assert (not (handoff-pending *handoff*)))
             (setf *app-actions* nil)
             ;; Local art/screenshot bypass the focused remote's passthrough/chord.
             (prefix)
             (dolist (type '(10 10 11)) (assert (probe-event 37 type +command+)))
             (assert (eq :launch (caar *app-actions*)))
             (assert (= 1 (length *app-actions*)))
             (setf *app-actions* nil)
             (prefix)
             (dolist (type '(10 10 11)) (assert (probe-event 105 type 0)))
             (assert (equal *app-actions* '((:activate nil "com.apple.screenshot.launcher"))))
             (assert (not *callback-error*))
             (assert (zerop (hash-table-count *app-down*)))))
      (cancel)
      (setf (symbol-function 'twigwm-macos-apps:frontmost) frontmost
            (symbol-function 'post-key-chord) post-chord)))
  (format t "PASS: previous-window prefix, prefix forwarding, unknown keys, Control-G/Tab/click cancellation, secondary zero, and local art/screenshots.~%"))
(format t "MACOS_INPUT_COMPLETE~%")
