;;;; Run with: ciel --no-userinit tests/macos-placement.lisp
(load (merge-pathnames "fixture.lisp" *load-truename*))
(in-package :twigwm-macos-apps)

(defparameter *test-screens*
  '(("00000000-0000-0000-0000-000000000001" (0 0 1440 2560) (0 31 1440 2529))
    ("00000000-0000-0000-0000-000000000002" (-2560 320 2560 1440) (-2560 320 2560 1440))
    ("00000000-0000-0000-0000-000000000003" (-1496 1760 1496 967) (-1496 1788 1496 939))))

(dolist (case '((:landscape-left (-2560 351 853 1409))
                (:landscape-right (-1707 351 1707 1409))
                (:portrait-top (0 31 1440 843))
                (:portrait-main (0 874 1440 1686))
                (:laptop (-1496 1788 1496 939))))
  (assert (equal (second case) (region-rect (first case) *test-screens*))))
(assert (null (region-rect :portrait-main (cdr *test-screens*))))
(assert (null (region-rect :laptop nil)))
(assert (null (region-rect nil *test-screens*)))
(assert (handler-case (progn (region-rect :typo *test-screens*) nil) (error () t)))
;; Resolution/origin changes and a larger menu/Dock exclusion use fresh geometry.
(let* ((screens (copy-tree *test-screens*))
       (screen (first screens)))
  (setf (second screen) '(1200 -600 1081 1921)
        (third screen) '(1200 -560 1081 1820))
  (let ((top (region-rect :portrait-top screens))
        (bottom (region-rect :portrait-main screens)))
    (assert (equal top '(1200 -560 1081 607)))
    (assert (= (+ (second top) (fourth top)) (second bottom)))
    (assert (= (+ (fourth top) (fourth bottom)) 1820))))
(format t "PASS: five regions, shared rounded edges, negative origins, menu/Dock clearance, missing displays.~%")

(dolist (case '((:landscape-left :right :landscape-right)
                (:landscape-right :left :landscape-left)
                (:landscape-right :right :portrait-main)
                (:portrait-main :left :landscape-right)
                (:portrait-top :down :portrait-main)
                (:portrait-main :up :portrait-top)
                (:landscape-right :down :laptop)
                (:laptop :up :landscape-right)
                (:landscape-left :left nil)
                (:portrait-main :right nil)
                (:laptop :down nil)))
  (destructuring-bind (region direction expected) case
    (assert (eq expected (neighbor-region (region-rect region *test-screens*)
                                             direction *test-screens*)))))
(assert (null (neighbor-region '(0 0 100 100) :right nil)))
(assert (null (neighbor-region (region-rect :landscape-right *test-screens*)
                                  :right (cdr *test-screens*))))
;; A manually sized/offset window starts from the region it overlaps most.
(assert (eq :landscape-right (neighbor-region '(-2500 400 900 1000) :right *test-screens*)))
(format t "PASS: directional neighbors, overlap tie-breaking, monitor gaps, edges, disconnected screens.~%")

(defmacro with-test-functions (bindings &body body)
  (let ((saved (gensym)))
    `(let ((,saved (mapcar (lambda (name) (cons name (symbol-function name)))
                          ',(mapcar #'first bindings))))
       (unwind-protect
            (progn ,@(loop for (name function) in bindings
                           collect `(setf (symbol-function ',name) ,function))
                   ,@body)
         (dolist (pair ,saved) (setf (symbol-function (car pair)) (cdr pair)))))))

;; Windows App's multi-monitor windows report AXFullScreen=false even while
;; covering a complete display. Their arrows belong to the remote WM.
(let ((fullscreen nil) (rect '(-2560 320 2560 1440)))
  (with-test-functions
      ((ax-flag-p (lambda (window name)
                    (declare (ignore window))
                    (assert (equal name "AXFullScreen")) fullscreen))
       (ax-pair (lambda (window name type)
                  (declare (ignore window type))
                  (if (equal name "AXPosition") (subseq rect 0 2) (subseq rect 2))))
       (screens (lambda () *test-screens*)))
    (assert (remote-fullscreen-window-p :selected))
    (setf rect '(0 31 1440 2529))
    (assert (remote-fullscreen-window-p :selected))
    (setf rect '(0 874 1440 1686))
    (assert (not (remote-fullscreen-window-p :selected)))
    (setf rect '(200 200 1000 700))
    (assert (not (remote-fullscreen-window-p :selected)))
    (setf fullscreen t)
    (assert (remote-fullscreen-window-p :selected))))
(format t "PASS: borderless remote fullscreen, visible screen bounds, tiled/windowed clients, native fullscreen.~%")

(let ((calls nil) (flag nil) (role "AXStandardWindow"))
  (with-test-functions
      ((ax-flag-p (lambda (window name) (assert (eq window :selected)) (equal name flag)))
       (ax-text (lambda (window name)
                     (assert (eq window :selected)) (assert (equal name "AXSubrole")) role))
       (ax-pair (lambda (window name type)
                  (declare (ignore window type))
                  (if (equal name "AXPosition") '(0 874) '(1440 1686))))
       (ax-set-pair (lambda (window name type values)
                        (assert (eq window :selected)) (push (list name type values) calls))))
    (dotimes (i 2) (assert (eq :placed (place-window :selected '(0 874 1440 1686)))))
    (assert (equal (reverse calls)
                   (loop repeat 2 append '(("AXSize" 2 (1440 1686))
                                          ("AXPosition" 1 (0 874))
                                          ("AXSize" 2 (1440 1686))
                                          ("AXPosition" 1 (0 874))))))
    (setf calls nil flag "AXFullScreen")
    (assert (eq :fullscreen (place-window :selected '(0 0 1 1))))
    (setf flag "AXMinimized")
    (assert (eq :minimized (place-window :selected '(0 0 1 1))))
    (setf flag nil role "AXDialog")
    (assert (eq :nonstandard (place-window :selected '(0 0 1 1))))
    (assert (null calls))))
(format t "PASS: selected-window-only placement repeats; fullscreen, minimized windows and dialogs untouched.~%")

;; Model the observed cross-display Chrome constraint: moving a too-wide window
;; first makes its next shrink stop 24 points short. Growing on the shorter
;; source screen is also constrained until the move has happened.
(let ((position '(0 874)) (size '(1440 1686)) (crossed-wide nil))
  (with-test-functions
      ((ax-flag-p (lambda (&rest args) (declare (ignore args)) nil))
       (ax-text (lambda (&rest args) (declare (ignore args)) "AXStandardWindow"))
       (ax-pair (lambda (window name type)
                  (declare (ignore window type))
                  (if (equal name "AXPosition") position size)))
       (ax-set-pair
        (lambda (window name type values)
          (declare (ignore window type))
          (cond ((equal name "AXPosition")
                 (setf crossed-wide (and (>= (first position) 0) (< (first values) 0)
                                         (> (first size) 1280))
                       position values))
                (t (setf size (list (+ (first values) (if crossed-wide 24 0))
                                   (if (< (first position) 0) (min 1409 (second values))
                                       (second values)))
                         crossed-wide nil))))))
    (place-window :chrome '(-1280 351 1280 1409))
    (assert (equal (append position size) '(-1280 351 1280 1409)))
    (place-window :chrome '(0 874 1440 1686))
    (assert (equal (append position size) '(0 874 1440 1686)))))
(format t "PASS: shrink before crossing monitors; grow again on the destination without a delay.~%")

;; Applications can adjust their position while accepting the final size,
;; round down to character cells, temporarily reject AX writes, or enforce a
;; minimum size. Only report successful placement when the actual window fits.
(let ((position '(100 100)) (size '(400 400)) (mode :drift) (writes 0))
  (with-test-functions
      ((ax-flag-p (lambda (&rest args) (declare (ignore args)) nil))
       (ax-text (lambda (&rest args) (declare (ignore args)) "AXStandardWindow"))
       (ax-pair (lambda (window name type)
                  (declare (ignore window type))
                  (if (equal name "AXPosition") position size)))
       (ax-set-pair
        (lambda (window name type values)
          (declare (ignore window type))
          (incf writes)
          (when (and (eq mode :transient) (= writes 1))
            (error "Transient Accessibility failure"))
          (if (equal name "AXPosition")
              (setf position values)
              (progn
                (setf size (case mode
                             (:cells (mapcar (lambda (n) (- n 7)) values))
                             (:minimum (list (max 1000 (first values)) (second values)))
                             (t values)))
                (when (eq mode :drift) (setf position '(120 120))))))))
    (dolist (behavior '(:drift :cells :transient))
      (setf mode behavior writes 0)
      (assert (eq :placed (place-window :selected '(-2560 248 853 1440))))
      (assert (equal position '(-2560 248)))
      (assert (every #'<= size '(853 1440))))
    (setf mode :minimum writes 0)
    (assert (handler-case
                (progn (place-window :selected '(-2560 248 853 1440)) nil)
              (error (e) (search "Window did not fit" (princ-to-string e)))))
    (assert (<= writes 12))))
(format t "PASS: resize-induced drift corrected, cell rounding accepted, transient errors retried, impossible fits bounded and reported.~%")

(let ((result :placed) (calls nil) (remembered nil))
  (with-test-functions
      ((screens (lambda () *test-screens*))
       (ax-timeout (lambda (&rest args) (declare (ignore args))))
       (ax-pair (lambda (window name type)
                    (declare (ignore window type))
                    (if (equal name "AXPosition") '(-2560 351) '(853 1409))))
       (place-window (lambda (window rect) (push (list window rect) calls) result))
       (remember-window (lambda (window bundle) (push (cons window bundle) remembered))))
    (move-window :one :right "app.one")
    (assert (equal calls '((:one (-1707 351 1707 1409)))))
    (assert (equal remembered '((:one . "app.one"))))
    (dolist (skip '(:fullscreen :minimized :nonstandard))
      (setf result skip)
      (move-window :two :right "app.two"))
    (assert (= 1 (length remembered)))
    (setf calls nil result :placed)
    (move-window :one :left "app.one")
    (assert (equal calls '((:one (-2560 351 853 1409)))))
    (assert (= 2 (length remembered)))))
(format t "PASS: arrows snap to tiles and record only placed windows; skipped moves record nothing.~%")

;; One memory: loaded from the file, updated by arrows, applied to new windows.
(let* ((*desktop-file* (merge-pathnames (format nil "twigwm-memory-~d/desktop.sexp" (random 1000000))
                                        (uiop:temporary-directory)))
       (*desktop* nil) (*desktop-date* :unread) (*seen* nil)
       (windows (list (list :chrome "Inbox" "AXStandardWindow" '(1 1 100 100))
                      (list :zoom "" "AXSystemDialog" '(5 5 240 135))))
       (open '((1 . "com.google.Chrome") (2 . "us.zoom.xos")))
       (applied nil) (released nil))
  (flet ((window (key) (assoc key windows))
         (write-file (entries)
           (with-open-file (s (ensure-directories-exist *desktop-file*) :direction :output
                                                                        :if-exists :supersede)
             (with-standard-io-syntax (write entries :stream s)))))
    (unwind-protect
         (with-test-functions
             ((framework (lambda (name) (declare (ignore name))))
              (running-apps (lambda () open))
              (app-windows (lambda (pid function)
                             (dolist (w (if (= pid 1) '(:chrome) '(:zoom))) (funcall function w))))
              (ax-flag-p (lambda (&rest args) (declare (ignore args)) nil))
              (ax-title (lambda (w) (second (window w))))
              (ax-text (lambda (w name) (declare (ignore name)) (third (window w))))
              (window-frame (lambda (w) (fourth (window w))))
              (cf-equal #'eq)
              (retain #'identity)
              (release (lambda (w) (push w released)))
              (apply-frame (lambda (w frame) (push (cons w frame) applied))))
           (write-file '((:bundle "us.zoom.xos" :title "" :subrole "AXSystemDialog"
                          :frame (-832 -876 640 360))))
           (load-memory)
           ;; Service start records open windows without moving them.
           (place-new-windows nil)
           (assert (null applied))
           (assert (= 2 (length *seen*)))
           (place-new-windows)
           (assert (null applied))
           ;; A new meeting window with an entry is placed once; unknown ones are left alone.
           (setf *seen* (remove :zoom *seen* :key #'car))
           (push (list :other "x" "AXStandardWindow" '(0 0 9 9)) windows)
           (place-new-windows)
           (place-new-windows)
           (assert (equal applied '((:zoom -832 -876 640 360))))
           ;; Arrows update memory, not the file; a later new window uses the memory.
           (remember-window :chrome "com.google.Chrome")
           (assert (= 1 (length (read-desktop))))
           (assert (equal '(1 1 100 100) (getf (window-entry :chrome "com.google.Chrome") :frame)))
           ;; save-desktop rewrites the file; the memory follows it without a restart.
           (sleep 1.1)
           (let ((*standard-output* (make-broadcast-stream))) (save-desktop))
           (setf (fourth (window :zoom)) '(7 7 240 135))
           (sleep 1.1)
           (let ((*standard-output* (make-broadcast-stream))) (save-desktop))
           (assert (equal '(7 7 240 135) (getf (window-entry :zoom "us.zoom.xos") :frame)))
           ;; An app that exits releases its windows; the others stay seen.
           (setf open '((1 . "com.google.Chrome")))
           (place-new-windows)
           (assert (equal released '(:zoom)))
           (assert (null (find :zoom *seen* :key #'car)))
           (reset-seen)
           (assert (null *seen*)))
      (uiop:delete-directory-tree (uiop:pathname-directory-pathname *desktop-file*)
                                  :validate t :if-does-not-exist :ignore))))
(format t "PASS: memory loads from file, start records without moving, new windows placed once, arrows update memory not the file, save-desktop reloads.~%")

(let ((calls nil)
      (app (find "vterm" twigwm-apps:*apps* :key #'twigwm-apps:app-name :test #'equal)))
  (with-test-functions
      ((open-bundle (lambda (bundle) (push (list :open bundle) calls)))
       (output (lambda (argv) (push (list :select argv) calls)))
       (place-bundle (lambda (bundle region &optional pid)
                          (assert (null pid)) (push (list :place bundle region) calls))))
    (dotimes (i 2) (twigwm-macos-input::activate-app app "org.gnu.Emacs"))
    (assert (equal (reverse calls)
                   (loop repeat 2 append
                     (list '(:open "org.gnu.Emacs")
                           (list :select (twigwm-apps:app-mac-cmd app))
                           '(:place "org.gnu.Emacs" :landscape-left)))))))
;; Disabled placement does no native work; failures do not break app focus.
(with-test-functions
    ((place-bundle (lambda (&rest args) (error "placement unavailable: ~s" args))))
  (let ((*error-output* (make-string-output-stream)))
    (twigwm-macos-input::place-app (twigwm-apps:make-app :mac-region nil) "disabled")
    (assert (equal "" (get-output-stream-string *error-output*)))
    (twigwm-macos-input::place-app (twigwm-apps:make-app) "test.bundle")
    (assert (search "Window placement failed" (get-output-stream-string *error-output*)))))
(format t "PASS: every activation places after frame selection; disabled/error paths preserve activation.~%")

(when (uiop:os-macosx-p)
  (framework "ApplicationServices")
  (let ((screens (screens)))
    (assert screens)
    (dolist (screen screens)
      (assert (= 36 (length (first screen))))
      (assert (every #'plusp (cddr (second screen)))))
    (format t "PASS: native display UUIDs/geometry read without moving windows: ~s~%" screens))
  (multiple-value-bind (pid bundle) (frontmost)
    (let ((window (movable-window pid nil)))
      (if (not window)
          (format t "SKIP: no responsive focused AX window in ~a.~%" bundle)
          (with-cf (selected window)
            (with-cf (again (movable-window pid nil))
              (assert (cf-equal selected again)))
            (let ((position (ax-pair selected "AXPosition" 1))
                  (size (ax-pair selected "AXSize" 2))
                  (fullscreen (ax-flag-p selected "AXFullScreen")))
              (assert (every #'plusp size))
              (format t "PASS: live AX identity, geometry and fullscreen read only: ~a ~s ~s fullscreen=~s.~%"
                      bundle position size fullscreen))))))
  ;; Use owned CF objects as window identities and mock AX reads/moves. Exercise
  ;; the real retention, CFEqual and release of the watcher's seen windows.
  (with-cf (one (cf-string "window one"))
    (with-cf (same (cf-string "window one"))
      (let ((*seen* nil) (*desktop* nil) (*desktop-date* nil) (selected same) (calls nil)
            (pid (cffi:foreign-funcall "getpid" :int)))
        (unwind-protect
             (with-test-functions
                 ((screens (lambda () *test-screens*))
                  (desktop-memory (lambda () *desktop*))
                  (ax-flag-p (lambda (window name)
                               (declare (ignore window)) (equal name "AXFrontmost")))
                  (ax-text (lambda (&rest args) (declare (ignore args)) "AXStandardWindow"))
                  (ax-title (lambda (window) (declare (ignore window)) "w"))
                  (ax-get (lambda (app name)
                            (declare (ignore app)) (assert (equal name "AXFocusedWindow"))
                            (cffi:foreign-funcall "CFRetain" :pointer selected :pointer)))
                  (running-apps (lambda () (list (cons pid "test"))))
                  (app-windows (lambda (p function) (declare (ignore p)) (funcall function selected)))
                  (apply-frame (lambda (&rest args) (declare (ignore args))))
                  (place-window (lambda (window rect) (push (list window rect) calls) :placed)))
               ;; Command-N: memory frame first, configured region otherwise.
               (place-bundle "test" :portrait-main pid)
               (setf *desktop* '((:bundle "test" :title "w" :subrole "AXStandardWindow"
                                  :frame (10 20 300 200))))
               (place-bundle "test" :portrait-main pid)
               (assert (equal (mapcar #'second calls) '((10 20 300 200) (0 874 1440 1686))))
               ;; Equal AX identities are one seen window, retained once.
               (place-new-windows nil)
               (setf selected one)
               (place-new-windows nil)
               (assert (= 1 (length *seen*))))
          (reset-seen)))))
  (format t "PASS: native CF window identity/ownership; Command-N prefers memory frames over regions.~%"))
(in-package :twigwm-macos-input)
(dolist (case '((123 . :left) (124 . :right) (125 . :down) (126 . :up)))
  (assert (eq (cdr case) (movement-direction (car case) +command+)))
  (dolist (flags '(0 #x80000 #x180000 #x120000 #x140000))
    (assert (null (movement-direction (car case) flags)))))
(assert (null (movement-direction 48 +command+)))
(format t "PASS: only Command-arrows move windows; Option/Shift/Control variants and Command-Tab untouched.~%")

(when (uiop:os-macosx-p)
  ;; Direct callback invocation, no tap or event delivery. The AX window is a
  ;; retained CF test identity; only app/window reads and movement are mocked.
  (twigwm-macos-apps::with-cf (window (twigwm-macos-apps::cf-string "movement test window"))
    (let ((*live* t) (*handoff* (make-handoff)) (*lease* nil)
          (*escape-down* nil)
          (*callback-error* nil) (*probe-seen* nil)
          (*remote-bundles* '("com.citrix.receiver.icaviewer.mac" "com.microsoft.rdc.macos"))
          (*app-down* (make-hash-table)) (*app-actions* nil) (*app-thread* nil)
          (bundle "com.apple.finder") (fullscreen nil) (unavailable nil) (moves nil)
          (rect '(20 20 500 400)))
      (unwind-protect
           (twigwm-macos-apps::with-test-functions
               ((twigwm-macos-apps:frontmost (lambda () (values 123 bundle)))
                (twigwm-macos-apps::ax-timeout (lambda (&rest args) (declare (ignore args))))
                (twigwm-macos-apps::ax-get
                 (lambda (app name)
                   (declare (ignore app)) (assert (equal name "AXFocusedWindow"))
                   (when unavailable (error "AX unavailable"))
                   (cffi:foreign-funcall "CFRetain" :pointer window :pointer)))
                (twigwm-macos-apps::ax-flag-p
                 (lambda (selected name)
                   (assert (twigwm-macos-apps::cf-equal selected window))
                   (assert (equal name "AXFullScreen")) fullscreen))
                (twigwm-macos-apps::ax-pair
                 (lambda (selected name type)
                   (declare (ignore selected type))
                   (if (equal name "AXPosition") (subseq rect 0 2) (subseq rect 2))))
                (twigwm-macos-apps:screens
                 (lambda () twigwm-macos-apps::*test-screens*))
                (twigwm-macos-apps:move-window
                 (lambda (selected direction moved-bundle)
                   (assert (twigwm-macos-apps::cf-equal selected window))
                   (assert (equal moved-bundle bundle))
                   (push direction moves))))
             (dolist (app (cons "com.apple.finder" *remote-bundles*))
               (setf bundle app fullscreen nil)
               (dolist (code '(123 124 125 126))
                 (assert (probe-event code 10 +command+))
                 (assert (probe-event code 10 +command+)) ; held repeat
                 (assert (= 1 (length *app-actions*)))
                 (assert (probe-event code 11 0)) ; release after Command released
                 (service-apps)
                 (sb-thread:join-thread *app-thread*)
                 (assert (eq (first moves) (movement-direction code +command+)))
                 (assert (null *app-actions*)))
               (dolist (flags '(0 #x180000 #x120000 #x140000))
                 (assert (not (probe-event 123 10 flags)))
                 (assert (not (probe-event 123 11 flags)))))
             (dolist (app *remote-bundles*)
               (setf bundle app)
               (dolist (native-fullscreen '(t nil))
                 (setf fullscreen native-fullscreen rect '(-2560 320 2560 1440))
                 (dolist (code '(123 124 125 126))
                   (assert (not (probe-event code 10 +command+)))
                   (assert (not (probe-event code 11 +command+)))))
               (assert (null *app-actions*)))
             ;; Preserve down/up already consumed if fullscreen/focus changes.
             (setf fullscreen nil rect '(20 20 500 400))
             (assert (probe-event 123 10 +command+))
             (setf fullscreen t)
             (assert (probe-event 123 11 +command+))
             (service-apps)
             (sb-thread:join-thread *app-thread*)
             (setf unavailable t)
             (assert (not (probe-event 123 10 +command+)))
             (assert (not (probe-event 123 11 +command+)))
             (setf unavailable nil)
             ;; Buffered input makes the same fullscreen decision at its target.
             (arm *handoff*)
             (assert (probe-event 124 10 +command+))
             (assert (probe-event 124 11 +command+))
             (dolist (event (reverse (handoff-events *handoff*)))
               (assert (not (dispatch-native-key event 456 bundle))))
             (setf fullscreen nil)
             (dolist (event (reverse (handoff-events *handoff*)))
               (assert (dispatch-native-key event 456 bundle)))
             (assert (= 1 (length *app-actions*)))
             (assert (zerop (hash-table-count *app-down*)))
             (assert (null *callback-error*)))
        (cancel)
        (dolist (action *app-actions*) (release-app-action action)))))
  (format t "PASS: native callback moves/worker, fullscreen remote passthrough, key releases, buffered dispatch, AX failure passthrough.~%"))

(in-package :twigwm-macos-apps)
(let ((entries '((:bundle "us.zoom.xos" :title "Zoom Meeting" :subrole "AXStandardWindow" :frame (0 31 1440 843))
                 (:bundle "us.zoom.xos" :title "" :subrole "AXFloatingWindow" :frame (1100 60 320 180))
                 (:bundle "com.google.Chrome" :title "a" :subrole "AXStandardWindow" :frame (1 2 3 4))
                 (:bundle "com.google.Chrome" :title "b" :subrole "AXStandardWindow" :frame (5 6 7 8)))))
  (assert (equal '(0 31 1440 843) (getf (saved-entry entries "us.zoom.xos" "Zoom Meeting" "AXStandardWindow") :frame)))
  (assert (equal '(1100 60 320 180) (getf (saved-entry entries "us.zoom.xos" "renamed" "AXFloatingWindow") :frame)))
  (assert (equal '(5 6 7 8) (getf (saved-entry entries "com.google.Chrome" "b" "AXStandardWindow") :frame)))
  ;; Two unmatched same-subrole windows are ambiguous; unknown apps are left alone.
  (assert (null (getf (saved-entry entries "com.google.Chrome" "c" "AXStandardWindow") :frame)))
  (assert (null (getf (saved-entry entries "org.gnu.Emacs" "x" "AXStandardWindow") :frame))))
(format t "PASS: saved desktop matches exact titles, then one window per bundle/subrole, including floating windows.~%")
(let* ((*desktop-file* (merge-pathnames (format nil "twigwm-test-~d/desktop.sexp" (random 1000000))
                                        (uiop:temporary-directory)))
       (frames (list (list :selected '(10 20 300 200)))) (moves nil))
  (unwind-protect
       (with-test-functions
           ((framework (lambda (name) (declare (ignore name))))
            (running-apps (lambda () '((1 . "us.zoom.xos"))))
            (app-windows (lambda (pid function) (declare (ignore pid)) (funcall function :selected)))
            (ax-flag-p (lambda (&rest args) (declare (ignore args)) nil))
            (ax-title (lambda (window) (declare (ignore window)) ""))
            (ax-text (lambda (window name) (declare (ignore window name)) "AXFloatingWindow"))
            (window-frame (lambda (window) (second (assoc window frames))))
            (ax-set-pair (lambda (window name type values)
                           (declare (ignore window type)) (push (cons name values) moves))))
         (let ((*standard-output* (make-broadcast-stream)))
           (save-desktop)
           (load-desktop))
         (assert (equal (reverse moves) '(("AXPosition" 10 20) ("AXSize" 300 200) ("AXPosition" 10 20))))
         ;; Merge, not overwrite: a closed window keeps its entry, the open one moves.
         (with-open-file (stream *desktop-file* :direction :output :if-exists :supersede)
           (with-standard-io-syntax
             (write '((:bundle "us.zoom.xos" :title "" :subrole "AXFloatingWindow" :frame (1 1 1 1))
                      (:bundle "us.zoom.xos" :title nil :subrole "AXFloatingWindow" :frame (2 2 2 2))
                      (:bundle "org.gnu.Emacs" :title "e" :subrole "AXStandardWindow" :frame (3 3 3 3)))
                    :stream stream)))
         (setf (second (first frames)) '(40 50 300 200))
         (let ((*standard-output* (make-broadcast-stream))) (save-desktop))
         (assert (equal (read-desktop)
                        '((:bundle "us.zoom.xos" :title "" :subrole "AXFloatingWindow" :frame (40 50 300 200))
                          (:bundle "us.zoom.xos" :title nil :subrole "AXFloatingWindow" :frame (2 2 2 2))
                          (:bundle "org.gnu.Emacs" :title "e" :subrole "AXStandardWindow" :frame (3 3 3 3))))))
    (uiop:delete-directory-tree (uiop:pathname-directory-pathname *desktop-file*)
                                :validate t :if-does-not-exist :ignore)))
(format t "PASS: save/load desktop round-trips a floating window's frame; saving merges, keeping closed windows.~%")
(format t "PLACEMENT_TESTS_COMPLETE~%")
