;;;; Run with: ciel --no-userinit tests/screenshot-keys.lisp
(load (merge-pathnames "fixture.lisp" *load-truename*))
(in-package :twigwm-macos-input)

(let ((spec (native-key-spec 105))
      (*remote-bundles* '("com.citrix.receiver.icaviewer.mac" "com.microsoft.rdc.macos")))
  (assert (equal "com.apple.screenshot.launcher"
                 (native-key-action spec 0 "com.apple.finder")))
  (assert (null (native-key-action spec 0 "com.citrix.receiver.icaviewer.mac")))
  (assert (equal '((55 12 #x100008) (56 12 #x12000a)
                    (23 10 #x12000a) (23 11 #x12000a)
                    (56 12 #x100008) (55 12 0))
                  (native-key-action spec 0 "com.microsoft.rdc.macos")))
  (dolist (flags '(#x20000 #x40000 #x80000 #x100000 #x120000))
    (assert (null (native-key-action spec flags "com.microsoft.rdc.macos")))
    (assert (null (native-key-action spec flags "com.apple.finder"))))
  ;; Do not revive legacy Mac remaps or intercept native Command-Shift-5.
  (dolist (code '(23 97 98 100 111)) (assert (null (native-key-spec code)))))
(dolist (binding '(("Print" . "screenshot-select") ("M-Print" . "screenshot-window")
                   ("s-Print" . "screenshot-screen") ("s-percent" . "screenshot-select")))
  (assert (equal (cdr binding)
                 (twigwm-keys:key-cmd
                  (find-if (lambda (key)
                             (member (car binding) (uiop:ensure-list (twigwm-keys:key-stump key))
                                     :test #'equal))
                           (twigwm-keys:stump-keys))))))
(assert (notany (lambda (key)
                  (intersection '("F12" "M-F12" "s-F12")
                                (uiop:ensure-list (twigwm-keys:key-stump key)) :test #'equal))
                (twigwm-keys:stump-keys)))
(format t "PASS: shared Print/s-S-5 binding, native Screenshot, Windows App chord, no F12 grabs, remote/modifier passthrough.~%")

(let ((open (symbol-function 'twigwm-macos-apps:open-bundle))
      (place (symbol-function 'twigwm-macos-apps:place-bundle))
      (command (symbol-function 'twigwm-macos-apps::output))
      (calls nil))
  (unwind-protect
       (progn
         (setf (symbol-function 'twigwm-macos-apps:open-bundle)
               (lambda (bundle) (push bundle calls))
               (symbol-function 'twigwm-macos-apps:place-bundle)
               (lambda (&rest args) (error "Screenshot must not be placed: ~s" args))
               (symbol-function 'twigwm-macos-apps::output)
               (lambda (&rest args) (error "Screenshot must not spawn a command: ~s" args)))
         (activate-app nil "com.apple.screenshot.launcher")
         (assert (equal calls '("com.apple.screenshot.launcher"))))
    (setf (symbol-function 'twigwm-macos-apps:open-bundle) open
          (symbol-function 'twigwm-macos-apps:place-bundle) place
          (symbol-function 'twigwm-macos-apps::output) command)))
(format t "PASS: Screenshot uses the existing bundle launcher, without placement or CLI helpers.~%")

;; Invoke the C callback directly: no event tap and no delivery to applications.
(when (uiop:os-macosx-p)
  (twigwm-macos-apps::framework "ApplicationServices")
  (let ((frontmost (symbol-function 'twigwm-macos-apps:frontmost))
        (post (symbol-function 'post-key-chord))
        (chords nil)
        (bundle "com.apple.finder")
        (*live* t) (*handoff* (make-handoff)) (*lease* nil)
        (*escape-down* nil)
        (*callback-error* nil) (*probe-seen* nil)
        (*remote-bundles* '("com.citrix.receiver.icaviewer.mac" "com.microsoft.rdc.macos"))
        (*app-down* (make-hash-table)) (*app-actions* nil))
    (unwind-protect
         (progn
           (setf (symbol-function 'twigwm-macos-apps:frontmost)
                 (lambda () (values 123 bundle))
                 (symbol-function 'post-key-chord)
                 (lambda (pid chord) (push (list pid chord) chords)))
           (assert (probe-event 105 10 0))
           (assert (equal *app-actions* '((:activate nil "com.apple.screenshot.launcher"))))
           (setf *app-actions* nil bundle "com.citrix.receiver.icaviewer.mac")
           (assert (probe-event 105 10 0)) ; repeat never opens a second toolbar
           (assert (null *app-actions*))
           (assert (probe-event 105 11 0)) ; consume release despite changed focus
           (assert (zerop (hash-table-count *app-down*)))
           (flet ((check-event (type flags)
                    (multiple-value-bind (consumed description) (probe-event 105 type flags)
                      (assert (not consumed))
                      (assert (equal description (list 105 type flags))))))
             (check-event 10 0) ; remote unchanged
             (check-event 11 0)
             (setf bundle "com.microsoft.rdc.macos")
             (assert (probe-event 105 10 0))
             (assert (equal chords (list (list 123 (native-key-action (native-key-spec 105) 0 bundle)))))
             (assert (eq t (gethash 105 *app-down*)))
             (setf bundle "com.apple.finder")
             (assert (probe-event 105 10 0)) ; repeat does not reopen the selector
             (assert (probe-event 105 11 0)) ; consume release despite changed focus
             (assert (= 1 (length chords)))
             (assert (zerop (hash-table-count *app-down*)))
             (setf bundle "com.microsoft.rdc.macos")
             (dolist (flags '(#x80000 #x100000))
               (check-event 10 flags)
               (check-event 11 flags)))
           (setf bundle "com.apple.finder")
           (assert (not (probe-event 105 10 #x80000)))
           (assert (not (probe-event 105 11 #x80000)))
           (assert (not (probe-event 23 10 #x120000))) ; native Cmd-Shift-5
           (assert (not (probe-event 23 11 #x120000)))
           ;; A prefix in flight queues the original Print down/up for desktop.
           (arm *handoff*)
           (assert (probe-event 105 10 0))
           (assert (probe-event 105 11 0))
           (assert (= 2 (handoff-count *handoff*)))
           (assert (every (lambda (event) (= 105 (event-field event 9)))
                          (handoff-events *handoff*)))
           ;; Replay uses the resolved destination, not the pre-handoff app.
           (dolist (event (reverse (handoff-events *handoff*)))
             (assert (not (dispatch-native-key event 456 "com.citrix.receiver.icaviewer.mac")))
             (assert (= 105 (event-field event 9))))
           (dolist (event (reverse (handoff-events *handoff*)))
             (assert (dispatch-native-key event 456 "com.microsoft.rdc.macos")))
           (assert (= 2 (length chords)))
           (assert (= 456 (first (first chords))))
           (assert (zerop (hash-table-count *app-down*)))
           (cancel)
           ;; The complete chord is already released; a later Print release is consumed.
           (setf bundle "com.microsoft.rdc.macos")
           (assert (probe-event 105 10 0))
           (arm *handoff*)
           (assert (probe-event 105 11 0))
           (assert (zerop (handoff-count *handoff*)))
           (assert (= 3 (length chords)))
           (assert (zerop (hash-table-count *app-down*)))
           (assert (null *app-actions*))
           (assert (not *callback-error*)))
      (cancel)
      (setf (symbol-function 'twigwm-macos-apps:frontmost) frontmost
            (symbol-function 'post-key-chord) post)))
  (format t "PASS: native dispatch, Windows App chord, consumed repeats/releases, modifiers and handoff buffering.~%"))
(format t "SCREENSHOT_KEYS_COMPLETE~%")
